package com.examquizai.backend.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a single answer option generated by the UiPath AI agent.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GeneratedOptionResponse {

    /**
     * Unique option ID.
     */
    private String id;

    /**
     * Option text displayed to the student.
     */
    private String text;

    /**
     * Whether this option is the correct answer.
     *
     * <p>
     * This field is used internally while saving and grading the quiz.
     * It should NOT be exposed through the public quiz response.
     * </p>
     */
    private boolean correct;
}