package com.examquizai.backend.dto.response;

import com.examquizai.backend.model.enums.DifficultyLevel;
import com.examquizai.backend.model.enums.EntranceExam;
import com.examquizai.backend.model.enums.QuestionType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.List;

/**
 * Outward-facing, pre-submission representation of a Quiz.
 *
 * Returned by:
 * POST /api/quizzes/generate
 * GET  /api/quizzes/{id}
 *
 * Correct answers are intentionally NOT included.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class QuizResponse {

    /**
     * Unique quiz ID.
     */
    private String id;

    /**
     * Quiz title generated by the AI agent.
     */
    private String title;

    /**
     * Quiz description.
     */
    private String description;

    /**
     * Entrance examination selected by the student.
     *
     * Examples:
     * JEE_MAIN
     * JEE_ADVANCED
     * NEET
     * CAT
     * GATE
     */
    private EntranceExam exam;

    /**
     * Subject selected by the student.
     *
     * Examples:
     * Physics
     * Chemistry
     * Mathematics
     * Biology
     */
    private String subject;

    /**
     * Topic selected by the student.
     *
     * Examples:
     * Kinematics
     * Thermodynamics
     * Genetics
     */
    private String topic;

    /**
     * Difficulty level.
     */
    private DifficultyLevel difficulty;

    /**
     * Overall question type.
     */
    private QuestionType questionType;

    /**
     * Total number of questions.
     */
    private int totalQuestions;

    /**
     * Public questions.
     *
     * QuizQuestionPublicResponse does not contain
     * correct answers.
     */
    private List<QuizQuestionPublicResponse> questions;

    /**
     * Quiz creation timestamp.
     */
    private Instant createdAt;
}