package com.examquizai.backend.repository;

import com.examquizai.backend.model.document.Quiz;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.mongodb.repository.MongoRepository;

/**
 * Data access for {@link Quiz} documents.
 */
public interface QuizRepository extends MongoRepository<Quiz, String> {

    /**
     * Quizzes generated by a given user, newest first — reserved for a future
     * "my generated quizzes" view; not required by the current endpoint set
     * but kept consistent with the indexed {@code createdBy} field on {@link Quiz}.
     */
    Page<Quiz> findByCreatedByOrderByCreatedAtDesc(String createdBy, Pageable pageable);
}
