export function Footer() {
  return (
    <footer className="border-t border-ink-100 bg-white px-4 py-4 text-center text-xs text-ink-400 dark:border-ink-800 dark:bg-ink-900 sm:px-6">
      <p>&copy; {new Date().getFullYear()} ExamQuiz AI. Quizzes generated by an AI agent — always double-check important results.</p>
    </footer>
  );
}
