package com.examquizai.backend.model.document;

import com.examquizai.backend.model.enums.DifficultyLevel;
import com.examquizai.backend.model.enums.EntranceExam;
import com.examquizai.backend.model.enums.QuestionType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "quizzes")
public class Quiz {

    @Id
    private String id;

    /**
     * Quiz title generated by the AI agent.
     */
    private String title;

    /**
     * Quiz description generated by the AI agent.
     */
    private String description;

    /**
     * Entrance examination selected by the student.
     *
     * Examples:
     * JEE_MAIN
     * JEE_ADVANCED
     * NEET
     * CAT
     * GATE
     */
    private EntranceExam exam;

    /**
     * Subject selected by the student.
     *
     * Examples:
     * Physics
     * Chemistry
     * Mathematics
     * Biology
     */
    private String subject;

    /**
     * Topic selected by the student.
     *
     * Examples:
     * Kinematics
     * Thermodynamics
     * Genetics
     */
    private String topic;

    /**
     * Overall difficulty of the quiz.
     */
    private DifficultyLevel difficulty;

    /**
     * Overall question type.
     */
    private QuestionType questionType;

    /**
     * User who generated the quiz.
     */
    private String createdBy;

    /**
     * Questions belonging to this quiz.
     */
    @Builder.Default
    private List<QuizQuestion> questions = new ArrayList<>();

    /**
     * Total number of questions.
     */
    private int totalQuestions;

    /**
     * Maximum possible score.
     */
    private double maxScore;

    /**
     * UiPath agent execution identifier.
     */
    private String agentExecutionId;

    /**
     * MongoDB creation timestamp.
     */
    @CreatedDate
    private Instant createdAt;

    /**
     * MongoDB last modification timestamp.
     */
    @LastModifiedDate
    private Instant updatedAt;
}