package com.examquizai.backend.service.impl;

import com.examquizai.backend.dto.request.QuizGenerationRequest;
import com.examquizai.backend.dto.request.SubmitAnswerRequest;
import com.examquizai.backend.dto.request.SubmitQuizAttemptRequest;
import com.examquizai.backend.dto.response.GeneratedOptionResponse;
import com.examquizai.backend.dto.response.GeneratedQuestionResponse;
import com.examquizai.backend.dto.response.PageResponse;
import com.examquizai.backend.dto.response.QuestionAnswerResponse;
import com.examquizai.backend.dto.response.QuizAttemptResponse;
import com.examquizai.backend.dto.response.QuizAttemptSummaryResponse;
import com.examquizai.backend.dto.response.QuizGenerationResponse;
import com.examquizai.backend.dto.response.QuizOptionPublicResponse;
import com.examquizai.backend.dto.response.QuizQuestionPublicResponse;
import com.examquizai.backend.dto.response.QuizResponse;
import com.examquizai.backend.exception.BadRequestException;
import com.examquizai.backend.exception.ResourceNotFoundException;
import com.examquizai.backend.model.document.Quiz;
import com.examquizai.backend.model.document.QuizAttempt;
import com.examquizai.backend.model.document.QuestionAnswer;
import com.examquizai.backend.model.document.QuizOption;
import com.examquizai.backend.model.document.QuizQuestion;
import com.examquizai.backend.model.document.User;
import com.examquizai.backend.model.enums.AttemptStatus;
import com.examquizai.backend.model.enums.QuestionType;
import com.examquizai.backend.repository.QuizAttemptRepository;
import com.examquizai.backend.repository.QuizRepository;
import com.examquizai.backend.repository.UserRepository;
import com.examquizai.backend.service.AiAgentService;
import com.examquizai.backend.service.QuizService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

import java.time.Instant;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

/**
 * Implements quiz generation (via the UiPath agent), retrieval, grading, and
 * attempt history.
 *
 * <p><b>Answer-key discipline:</b> {@link #generateQuiz} and {@link #getQuizById}
 * only ever build {@link QuizResponse}, whose nested question/option DTOs have
 * no fields capable of carrying a correct answer. {@link #submitQuiz} is the
 * single place correct answers are read from a {@link Quiz} and placed into a
 * response — and only after grading has actually happened.</p>
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class QuizServiceImpl implements QuizService {

    private final QuizRepository quizRepository;
    private final QuizAttemptRepository quizAttemptRepository;
    private final UserRepository userRepository;
    private final AiAgentService aiAgentService;

    // =========================================================================
    // Generate
    // =========================================================================

    @Override
    @Transactional
    public QuizResponse generateQuiz(QuizGenerationRequest request, String requesterEmail) {
        User requester = requireUser(requesterEmail);

        QuizGenerationResponse generated = aiAgentService.generateQuiz(request);

        Quiz quiz = toQuizEntity(generated, requester.getId());
        Quiz saved = quizRepository.save(quiz);

        log.info("Quiz '{}' generated by user {} ({} questions)", saved.getId(), requester.getId(), saved.getTotalQuestions());

        return toQuizResponse(saved);
    }

    private Quiz toQuizEntity(QuizGenerationResponse generated, String createdBy) {
        List<QuizQuestion> questions = new ArrayList<>();
        double maxScore = 0.0;

        for (GeneratedQuestionResponse gq : generated.getQuestions()) {
            List<QuizOption> options = new ArrayList<>();
            if (gq.getOptions() != null) {
                for (GeneratedOptionResponse go : gq.getOptions()) {
                    options.add(QuizOption.builder()
                            .id(StringUtils.hasText(go.getId()) ? go.getId() : UUID.randomUUID().toString())
                            .text(go.getText())
                            .correct(go.isCorrect())
                            .build());
                }
            }

            double points = gq.getPoints() > 0 ? gq.getPoints() : 1.0;
            maxScore += points;

            questions.add(QuizQuestion.builder()
                    .id(UUID.randomUUID().toString())
                    .questionText(gq.getQuestionText())
                    .questionType(gq.getQuestionType())
                    .options(options)
                    .correctAnswer(gq.getCorrectAnswer())
                    .explanation(gq.getExplanation())
                    .points(points)
                    .build());
        }

        return Quiz.builder()
                .title(generated.getQuizTitle())
                .description(generated.getDescription())
                .subject(generated.getSubject())
                .difficulty(generated.getDifficulty())
                .questionType(inferOverallQuestionType(questions))
                .createdBy(createdBy)
                .questions(questions)
                .totalQuestions(questions.size())
                .maxScore(maxScore)
                .agentExecutionId(generated.getAgentExecutionId())
                .build();
    }

    private QuestionType inferOverallQuestionType(List<QuizQuestion> questions) {
        Set<QuestionType> distinctTypes = new HashSet<>();
        for (QuizQuestion q : questions) {
            distinctTypes.add(q.getQuestionType());
        }
        if (distinctTypes.size() == 1) {
            return distinctTypes.iterator().next();
        }
        return QuestionType.MIXED;
    }

    // =========================================================================
    // Retrieve (pre-submission - no answer key)
    // =========================================================================

    @Override
    public QuizResponse getQuizById(String quizId) {
        Quiz quiz = requireQuiz(quizId);
        return toQuizResponse(quiz);
    }

    private QuizResponse toQuizResponse(Quiz quiz) {
        List<QuizQuestionPublicResponse> questions = quiz.getQuestions().stream()
                .map(this::toQuestionPublicResponse)
                .toList();

        return QuizResponse.builder()
                .id(quiz.getId())
                .title(quiz.getTitle())
                .description(quiz.getDescription())
                .subject(quiz.getSubject())
                .difficulty(quiz.getDifficulty())
                .questionType(quiz.getQuestionType())
                .totalQuestions(quiz.getTotalQuestions())
                .questions(questions)
                .createdAt(quiz.getCreatedAt())
                .build();
    }

    private QuizQuestionPublicResponse toQuestionPublicResponse(QuizQuestion question) {
        List<QuizOptionPublicResponse> options = question.getOptions().stream()
                .map(option -> QuizOptionPublicResponse.builder()
                        .id(option.getId())
                        .text(option.getText())
                        .build())
                .toList();

        return QuizQuestionPublicResponse.builder()
                .id(question.getId())
                .questionText(question.getQuestionText())
                .questionType(question.getQuestionType())
                .options(options)
                .points(question.getPoints())
                .build();
    }

    // =========================================================================
    // Submit / grade (the only place answers are revealed)
    // =========================================================================

    @Override
    @Transactional
    public QuizAttemptResponse submitQuiz(String quizId, SubmitQuizAttemptRequest request, String requesterEmail) {
        User requester = requireUser(requesterEmail);
        Quiz quiz = requireQuiz(quizId);

        Map<String, SubmitAnswerRequest> submittedByQuestionId = validateAndIndexAnswers(quiz, request);

        List<QuestionAnswer> gradedAnswers = new ArrayList<>();
        int correctCount = 0;
        double totalScore = 0.0;
        Instant now = Instant.now();

        for (QuizQuestion question : quiz.getQuestions()) {
            SubmitAnswerRequest submitted = submittedByQuestionId.get(question.getId());
            QuestionAnswer graded = gradeAnswer(question, submitted, now);
            gradedAnswers.add(graded);
            if (Boolean.TRUE.equals(graded.getCorrect())) {
                correctCount++;
            }
            totalScore += graded.getPointsAwarded() != null ? graded.getPointsAwarded() : 0.0;
        }

        // Note: this endpoint grades a full submission in a single call - there is
        // no separate "start attempt" endpoint in this module, so startedAt and
        // submittedAt coincide and durationSeconds is not tracked. A future
        // "start attempt" endpoint could capture true elapsed time if needed.
        QuizAttempt attempt = QuizAttempt.builder()
                .userId(requester.getId())
                .quizId(quiz.getId())
                .quizTitle(quiz.getTitle())
                .answers(gradedAnswers)
                .totalQuestions(quiz.getTotalQuestions())
                .correctAnswers(correctCount)
                .score(totalScore)
                .maxScore(quiz.getMaxScore())
                .status(AttemptStatus.EVALUATED)
                .startedAt(now)
                .submittedAt(now)
                .durationSeconds(0L)
                .build();

        QuizAttempt saved = quizAttemptRepository.save(attempt);

        log.info("Quiz {} submitted by user {}: {}/{} correct, score {}/{}",
                quiz.getId(), requester.getId(), correctCount, quiz.getTotalQuestions(), totalScore, quiz.getMaxScore());

        return toQuizAttemptResponse(saved, quiz);
    }

    /**
     * Validates the submission against the quiz's actual questions/options
     * before any grading happens, and returns the answers indexed by question id.
     */
    private Map<String, SubmitAnswerRequest> validateAndIndexAnswers(Quiz quiz, SubmitQuizAttemptRequest request) {
        Map<String, QuizQuestion> questionsById = new LinkedHashMap<>();
        for (QuizQuestion q : quiz.getQuestions()) {
            questionsById.put(q.getId(), q);
        }

        Map<String, SubmitAnswerRequest> submittedByQuestionId = new LinkedHashMap<>();

        for (SubmitAnswerRequest answer : request.getAnswers()) {
            QuizQuestion question = questionsById.get(answer.getQuestionId());
            if (question == null) {
                throw new BadRequestException(
                        "Submitted answer references unknown questionId '" + answer.getQuestionId()
                                + "' for quiz " + quiz.getId());
            }
            if (submittedByQuestionId.containsKey(answer.getQuestionId())) {
                throw new BadRequestException(
                        "Duplicate answer submitted for questionId '" + answer.getQuestionId() + "'");
            }

            if (requiresOptions(question.getQuestionType()) && answer.getSelectedOptionIds() != null) {
                Set<String> validOptionIds = new HashSet<>();
                for (QuizOption option : question.getOptions()) {
                    validOptionIds.add(option.getId());
                }
                for (String selectedId : answer.getSelectedOptionIds()) {
                    if (!validOptionIds.contains(selectedId)) {
                        throw new BadRequestException(
                                "Submitted answer for questionId '" + answer.getQuestionId()
                                        + "' references unknown optionId '" + selectedId + "'");
                    }
                }
            }

            submittedByQuestionId.put(answer.getQuestionId(), answer);
        }

        return submittedByQuestionId;
    }

    private boolean requiresOptions(QuestionType type) {
        return type == QuestionType.MULTIPLE_CHOICE || type == QuestionType.TRUE_FALSE;
    }

    /**
     * Grades a single question. Unanswered questions (no matching submission)
     * are treated as incorrect/zero points rather than rejected, so a partial
     * submission still produces a valid graded attempt.
     */
    private QuestionAnswer gradeAnswer(QuizQuestion question, SubmitAnswerRequest submitted, Instant gradedAt) {
        List<String> selectedOptionIds = submitted != null && submitted.getSelectedOptionIds() != null
                ? submitted.getSelectedOptionIds() : List.of();
        String textAnswer = submitted != null ? submitted.getTextAnswer() : null;

        boolean correct;
        if (requiresOptions(question.getQuestionType())) {
            Set<String> correctOptionIds = new HashSet<>();
            for (QuizOption option : question.getOptions()) {
                if (option.isCorrect()) {
                    correctOptionIds.add(option.getId());
                }
            }
            Set<String> submittedIds = new HashSet<>(selectedOptionIds);
            correct = !correctOptionIds.isEmpty() && submittedIds.equals(correctOptionIds);
        } else {
            // SHORT_ANSWER: simple case-insensitive exact match. A more sophisticated
            // (e.g. AI-assisted) grading strategy could replace this in a future iteration.
            String expected = question.getCorrectAnswer() != null ? question.getCorrectAnswer().trim() : "";
            String actual = textAnswer != null ? textAnswer.trim() : "";
            correct = !expected.isEmpty() && expected.equalsIgnoreCase(actual);
        }

        double pointsAwarded = correct ? question.getPoints() : 0.0;

        return QuestionAnswer.builder()
                .questionId(question.getId())
                .selectedOptionIds(selectedOptionIds)
                .textAnswer(textAnswer)
                .correct(correct)
                .pointsAwarded(pointsAwarded)
                .answeredAt(gradedAt)
                .build();
    }

    private QuizAttemptResponse toQuizAttemptResponse(QuizAttempt attempt, Quiz quiz) {
        Map<String, QuizQuestion> questionsById = new LinkedHashMap<>();
        for (QuizQuestion q : quiz.getQuestions()) {
            questionsById.put(q.getId(), q);
        }

        List<QuestionAnswerResponse> answerResponses = attempt.getAnswers().stream()
                .map(answer -> toAnswerResponseWithAnswerKey(answer, questionsById.get(answer.getQuestionId())))
                .toList();

        return QuizAttemptResponse.builder()
                .id(attempt.getId())
                .userId(attempt.getUserId())
                .quizId(attempt.getQuizId())
                .quizTitle(attempt.getQuizTitle())
                .answers(answerResponses)
                .totalQuestions(attempt.getTotalQuestions())
                .correctAnswers(attempt.getCorrectAnswers())
                .score(attempt.getScore())
                .maxScore(attempt.getMaxScore())
                .status(attempt.getStatus())
                .startedAt(attempt.getStartedAt())
                .submittedAt(attempt.getSubmittedAt())
                .durationSeconds(attempt.getDurationSeconds())
                .createdAt(attempt.getCreatedAt())
                .updatedAt(attempt.getUpdatedAt())
                .build();
    }

    /**
     * Builds a post-submission {@link QuestionAnswerResponse}, including the
     * answer key for this question. Only called from {@link #submitQuiz}, after
     * grading has already happened.
     */
    private QuestionAnswerResponse toAnswerResponseWithAnswerKey(QuestionAnswer answer, QuizQuestion question) {
        List<String> correctOptionIds = null;
        String correctAnswerText = null;
        String explanation = null;

        if (question != null) {
            if (requiresOptions(question.getQuestionType())) {
                correctOptionIds = question.getOptions().stream()
                        .filter(QuizOption::isCorrect)
                        .map(QuizOption::getId)
                        .toList();
            } else {
                correctAnswerText = question.getCorrectAnswer();
            }
            explanation = question.getExplanation();
        }

        return QuestionAnswerResponse.builder()
                .questionId(answer.getQuestionId())
                .selectedOptionIds(answer.getSelectedOptionIds())
                .textAnswer(answer.getTextAnswer())
                .correct(answer.getCorrect())
                .pointsAwarded(answer.getPointsAwarded())
                .answeredAt(answer.getAnsweredAt())
                .correctOptionIds(correctOptionIds)
                .correctAnswerText(correctAnswerText)
                .explanation(explanation)
                .build();
    }

    // =========================================================================
    // History
    // =========================================================================

    @Override
    public PageResponse<QuizAttemptSummaryResponse> getHistory(String requesterEmail, int page, int size) {
        User requester = requireUser(requesterEmail);
        Pageable pageable = PageRequest.of(page, size);

        Page<QuizAttempt> attempts = quizAttemptRepository.findByUserIdOrderByCreatedAtDesc(requester.getId(), pageable);

        return PageResponse.of(attempts, this::toSummaryResponse);
    }

    private QuizAttemptSummaryResponse toSummaryResponse(QuizAttempt attempt) {
        return QuizAttemptSummaryResponse.builder()
                .id(attempt.getId())
                .quizId(attempt.getQuizId())
                .quizTitle(attempt.getQuizTitle())
                .totalQuestions(attempt.getTotalQuestions())
                .correctAnswers(attempt.getCorrectAnswers())
                .score(attempt.getScore())
                .maxScore(attempt.getMaxScore())
                .status(attempt.getStatus())
                .startedAt(attempt.getStartedAt())
                .submittedAt(attempt.getSubmittedAt())
                .durationSeconds(attempt.getDurationSeconds())
                .build();
    }

    // =========================================================================
    // Shared lookups
    // =========================================================================

    private User requireUser(String email) {
        return userRepository.findByEmail(email)
                .orElseThrow(() -> new ResourceNotFoundException("User", "email", email));
    }

    private Quiz requireQuiz(String quizId) {
        return quizRepository.findById(quizId)
                .orElseThrow(() -> new ResourceNotFoundException("Quiz", "id", quizId));
    }
}
