package com.examquizai.backend.service.impl;

import com.examquizai.backend.dto.request.QuizGenerationRequest;
import com.examquizai.backend.dto.request.SubmitAnswerRequest;
import com.examquizai.backend.dto.request.SubmitQuizAttemptRequest;
import com.examquizai.backend.dto.response.GeneratedOptionResponse;
import com.examquizai.backend.dto.response.GeneratedQuestionResponse;
import com.examquizai.backend.dto.response.PageResponse;
import com.examquizai.backend.dto.response.QuestionAnswerResponse;
import com.examquizai.backend.dto.response.QuizAttemptResponse;
import com.examquizai.backend.dto.response.QuizAttemptSummaryResponse;
import com.examquizai.backend.dto.response.QuizGenerationResponse;
import com.examquizai.backend.dto.response.QuizOptionPublicResponse;
import com.examquizai.backend.dto.response.QuizQuestionPublicResponse;
import com.examquizai.backend.dto.response.QuizResponse;
import com.examquizai.backend.exception.BadRequestException;
import com.examquizai.backend.exception.ResourceNotFoundException;
import com.examquizai.backend.model.document.QuestionAnswer;
import com.examquizai.backend.model.document.Quiz;
import com.examquizai.backend.model.document.QuizAttempt;
import com.examquizai.backend.model.document.QuizOption;
import com.examquizai.backend.model.document.QuizQuestion;
import com.examquizai.backend.model.document.User;
import com.examquizai.backend.model.enums.AttemptStatus;
import com.examquizai.backend.model.enums.QuestionType;
import com.examquizai.backend.repository.QuizAttemptRepository;
import com.examquizai.backend.repository.QuizRepository;
import com.examquizai.backend.repository.UserRepository;
import com.examquizai.backend.service.AiAgentService;
import com.examquizai.backend.service.QuizService;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

import java.time.Instant;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

@Slf4j
@Service
@RequiredArgsConstructor
public class QuizServiceImpl implements QuizService {

    private final QuizRepository quizRepository;
    private final QuizAttemptRepository quizAttemptRepository;
    private final UserRepository userRepository;
    private final AiAgentService aiAgentService;

    // ============================================================
    // GENERATE QUIZ
    // ============================================================

    @Override
    @Transactional
    public QuizResponse generateQuiz(
            QuizGenerationRequest request,
            String requesterEmail
    ) {

        User requester = requireUser(requesterEmail);

        log.info(
                "Generating quiz: exam={}, subject={}, topic={}, difficulty={}, questions={}",
                request.getExam(),
                request.getSubject(),
                request.getTopic(),
                request.getDifficulty(),
                request.getNumberOfQuestions()
        );

        QuizGenerationResponse generated =
                aiAgentService.generateQuiz(request);

        if (generated == null) {
            throw new BadRequestException(
                    "AI agent returned an empty quiz"
            );
        }

        Quiz quiz = toQuizEntity(
                generated,
                request,
                requester.getId()
        );

        Quiz saved = quizRepository.save(quiz);

        log.info(
                "Quiz '{}' generated by user {} ({} questions)",
                saved.getId(),
                requester.getId(),
                saved.getTotalQuestions()
        );

        return toQuizResponse(saved);
    }

    // ============================================================
    // CONVERT AI RESPONSE -> QUIZ ENTITY
    // ============================================================
/**
 * Builds a human-friendly quiz title from what the student actually chose,
 * rather than trusting whatever generic title the UiPath agent returns
 * (e.g. "ExamQuiz AI Practice Test"). Falls back to the agent's title only
 * if no topic was provided.
 */
private String buildQuizTitle(QuizGenerationRequest request) {
    if (StringUtils.hasText(request.getTopic())) {
        return request.getTopic().trim();
    }
    return "Practice Quiz";
}
    private Quiz toQuizEntity(
            QuizGenerationResponse generated,
            QuizGenerationRequest request,
            String createdBy
    ) {

        List<QuizQuestion> questions = new ArrayList<>();

        double maxScore = 0.0;

        if (generated.getQuestions() != null) {

            for (GeneratedQuestionResponse gq :
                    generated.getQuestions()) {

                if (gq == null) {
                    continue;
                }

                List<QuizOption> options = new ArrayList<>();

                if (gq.getOptions() != null) {

                    for (GeneratedOptionResponse go :
                            gq.getOptions()) {

                        if (go == null) {
                            continue;
                        }

                        String optionId =
                                StringUtils.hasText(go.getId())
                                        ? go.getId()
                                        : UUID.randomUUID().toString();

                        QuizOption option =
                                QuizOption.builder()
                                        .id(optionId)
                                        .text(go.getText())
                                        .correct(go.isCorrect())
                                        .build();

                        options.add(option);
                    }
                }

                double points =
                        gq.getPoints() > 0
                                ? gq.getPoints()
                                : 1.0;

                maxScore += points;

                QuizQuestion question =
                        QuizQuestion.builder()
                                .id(UUID.randomUUID().toString())
                                .questionText(gq.getQuestionText())
                                .questionType(gq.getQuestionType())
                                .options(options)
                                .correctAnswer(gq.getCorrectAnswer())
                                .explanation(gq.getExplanation())
                                .points(points)
                                .build();

                questions.add(question);
            }
        }

        return Quiz.builder()
               .title(buildQuizTitle(request)) 
                .description(generated.getDescription())

                // Frontend selected exam
                .exam(request.getExam())

                // Frontend selected subject
                .subject(request.getSubject())

                // Frontend selected topic
                .topic(request.getTopic())

                // Frontend selected difficulty
                .difficulty(request.getDifficulty())

                // Determine overall question type
                .questionType(
                        inferOverallQuestionType(questions)
                )

                // User who generated quiz
                .createdBy(createdBy)

                // Generated questions
                .questions(questions)

                // Total questions
                .totalQuestions(questions.size())

                // Maximum possible score
                .maxScore(maxScore)

                // UiPath execution ID
                .agentExecutionId(
                        generated.getAgentExecutionId()
                )

                .build();
    }

    // ============================================================
    // DETERMINE QUESTION TYPE
    // ============================================================

    private QuestionType inferOverallQuestionType(
            List<QuizQuestion> questions
    ) {

        Set<QuestionType> distinctTypes =
                new HashSet<>();

        if (questions != null) {

            for (QuizQuestion question : questions) {

                if (question != null
                        && question.getQuestionType() != null) {

                    distinctTypes.add(
                            question.getQuestionType()
                    );
                }
            }
        }

        if (distinctTypes.size() == 1) {
            return distinctTypes.iterator().next();
        }

        if (distinctTypes.isEmpty()) {
            return QuestionType.MIXED;
        }

        return QuestionType.MIXED;
    }

    // ============================================================
    // GET QUIZ BY ID
    // ============================================================

    @Override
    public QuizResponse getQuizById(String quizId) {

        Quiz quiz = requireQuiz(quizId);

        return toQuizResponse(quiz);
    }

    // ============================================================
    // QUIZ ENTITY -> PUBLIC RESPONSE
    // ============================================================

    private QuizResponse toQuizResponse(
            Quiz quiz
    ) {

        List<QuizQuestionPublicResponse> questions =
                quiz.getQuestions() == null
                        ? List.of()
                        : quiz.getQuestions()
                        .stream()
                        .map(this::toQuestionPublicResponse)
                        .toList();

        return QuizResponse.builder()
                .id(quiz.getId())
                .title(quiz.getTitle())
                .description(quiz.getDescription())

                // Exam
                .exam(quiz.getExam())

                // Subject
                .subject(quiz.getSubject())

                // Topic
                .topic(quiz.getTopic())

                // Difficulty
                .difficulty(quiz.getDifficulty())

                // Question type
                .questionType(quiz.getQuestionType())

                // Total questions
                .totalQuestions(quiz.getTotalQuestions())

                // Public questions
                .questions(questions)

                // Created time
                .createdAt(quiz.getCreatedAt())

                .build();
    }

    // ============================================================
    // QUESTION -> PUBLIC RESPONSE
    // ============================================================

    private QuizQuestionPublicResponse
    toQuestionPublicResponse(
            QuizQuestion question
    ) {

        List<QuizOptionPublicResponse> options =
                question.getOptions() == null
                        ? List.of()
                        : question.getOptions()
                        .stream()
                        .map(
                                option ->
                                        QuizOptionPublicResponse
                                                .builder()
                                                .id(option.getId())
                                                .text(option.getText())
                                                .build()
                        )
                        .toList();

        return QuizQuestionPublicResponse
                .builder()
                .id(question.getId())
                .questionText(question.getQuestionText())
                .questionType(question.getQuestionType())
                .options(options)
                .points(question.getPoints())
                .build();
    }

    // ============================================================
    // SUBMIT QUIZ
    // ============================================================

    @Override
    @Transactional
    public QuizAttemptResponse submitQuiz(
            String quizId,
            SubmitQuizAttemptRequest request,
            String requesterEmail
    ) {

        User requester =
                requireUser(requesterEmail);

        Quiz quiz =
                requireQuiz(quizId);

        if (request == null) {
            throw new BadRequestException(
                    "Quiz submission request cannot be null"
            );
        }

        Map<String, SubmitAnswerRequest>
                submittedByQuestionId =
                validateAndIndexAnswers(
                        quiz,
                        request
                );

        List<QuestionAnswer> gradedAnswers =
                new ArrayList<>();

        int correctCount = 0;

        double totalScore = 0.0;

        Instant now = Instant.now();

        List<QuizQuestion> quizQuestions =
                quiz.getQuestions() == null
                        ? List.of()
                        : quiz.getQuestions();

        for (QuizQuestion question :
                quizQuestions) {

            SubmitAnswerRequest submitted =
                    submittedByQuestionId.get(
                            question.getId()
                    );

            QuestionAnswer graded =
                    gradeAnswer(
                            question,
                            submitted,
                            now
                    );

            gradedAnswers.add(graded);

            if (Boolean.TRUE.equals(
                    graded.getCorrect()
            )) {

                correctCount++;
            }

            if (graded.getPointsAwarded() != null) {

                totalScore +=
                        graded.getPointsAwarded();
            }
        }

        QuizAttempt attempt =
                QuizAttempt.builder()
                        .userId(requester.getId())
                        .quizId(quiz.getId())
                        .quizTitle(quiz.getTitle())
                        .answers(gradedAnswers)
                        .totalQuestions(
                                quiz.getTotalQuestions()
                        )
                        .correctAnswers(
                                correctCount
                        )
                        .score(totalScore)
                        .maxScore(quiz.getMaxScore())
                        .status(
                                AttemptStatus.EVALUATED
                        )
                        .startedAt(now)
                        .submittedAt(now)
                        .durationSeconds(0L)
                        .build();

        QuizAttempt saved =
                quizAttemptRepository.save(attempt);

        log.info(
                "Quiz {} submitted by user {}: {}/{} correct, score {}/{}",
                quiz.getId(),
                requester.getId(),
                correctCount,
                quiz.getTotalQuestions(),
                totalScore,
                quiz.getMaxScore()
        );

        return toQuizAttemptResponse(
                saved,
                quiz
        );
    }

    // ============================================================
    // VALIDATE ANSWERS
    // ============================================================

    private Map<String, SubmitAnswerRequest>
    validateAndIndexAnswers(
            Quiz quiz,
            SubmitQuizAttemptRequest request
    ) {

        Map<String, QuizQuestion>
                questionsById =
                new LinkedHashMap<>();

        List<QuizQuestion> questions =
                quiz.getQuestions() == null
                        ? List.of()
                        : quiz.getQuestions();

        for (QuizQuestion question :
                questions) {

            questionsById.put(
                    question.getId(),
                    question
            );
        }

        Map<String, SubmitAnswerRequest>
                submittedByQuestionId =
                new LinkedHashMap<>();

        if (request.getAnswers() == null) {
            return submittedByQuestionId;
        }

        for (SubmitAnswerRequest answer :
                request.getAnswers()) {

            if (answer == null) {
                continue;
            }

            String questionId =
                    answer.getQuestionId();

            if (!StringUtils.hasText(questionId)) {

                throw new BadRequestException(
                        "questionId is required"
                );
            }

            QuizQuestion question =
                    questionsById.get(questionId);

            if (question == null) {

                throw new BadRequestException(
                        "Submitted answer references unknown questionId '"
                                + questionId
                                + "' for quiz "
                                + quiz.getId()
                );
            }

            if (submittedByQuestionId.containsKey(
                    questionId
            )) {

                throw new BadRequestException(
                        "Duplicate answer submitted for questionId '"
                                + questionId
                                + "'"
                );
            }

            // Validate selected option IDs
            if (requiresOptions(
                    question.getQuestionType()
            )
                    && answer.getSelectedOptionIds() != null) {

                Set<String> validOptionIds =
                        new HashSet<>();

                if (question.getOptions() != null) {

                    for (QuizOption option :
                            question.getOptions()) {

                        validOptionIds.add(
                                option.getId()
                        );
                    }
                }

                for (String selectedId :
                        answer.getSelectedOptionIds()) {

                    if (!validOptionIds.contains(
                            selectedId
                    )) {

                        throw new BadRequestException(
                                "Submitted answer for questionId '"
                                        + questionId
                                        + "' references unknown optionId '"
                                        + selectedId
                                        + "'"
                        );
                    }
                }
            }

            submittedByQuestionId.put(
                    questionId,
                    answer
            );
        }

        return submittedByQuestionId;
    }

    // ============================================================
    // QUESTION TYPES THAT USE OPTIONS
    // ============================================================

    private boolean requiresOptions(
            QuestionType type
    ) {

        return type == QuestionType.MULTIPLE_CHOICE
                || type == QuestionType.TRUE_FALSE;
    }

    // ============================================================
    // GRADE ONE ANSWER
    // ============================================================

    private QuestionAnswer gradeAnswer(
            QuizQuestion question,
            SubmitAnswerRequest submitted,
            Instant gradedAt
    ) {

        List<String> selectedOptionIds =
                submitted != null
                        && submitted.getSelectedOptionIds() != null
                        ? submitted.getSelectedOptionIds()
                        : List.of();

        String textAnswer =
                submitted != null
                        ? submitted.getTextAnswer()
                        : null;

        boolean correct;

        // --------------------------------------------------------
        // Multiple choice / True-False
        // --------------------------------------------------------

        if (requiresOptions(
                question.getQuestionType()
        )) {

            Set<String> correctOptionIds =
                    new HashSet<>();

            if (question.getOptions() != null) {

                for (QuizOption option :
                        question.getOptions()) {

                    if (option.isCorrect()) {

                        correctOptionIds.add(
                                option.getId()
                        );
                    }
                }
            }

            Set<String> submittedIds =
                    new HashSet<>(
                            selectedOptionIds
                    );

            correct =
                    !correctOptionIds.isEmpty()
                            && submittedIds.equals(
                            correctOptionIds
                    );

        } else {

            // ----------------------------------------------------
            // Text / subjective answer
            // ----------------------------------------------------

            String expected =
                    question.getCorrectAnswer() != null
                            ? question.getCorrectAnswer()
                            .trim()
                            : "";

            String actual =
                    textAnswer != null
                            ? textAnswer.trim()
                            : "";

            correct =
                    !expected.isEmpty()
                            && expected.equalsIgnoreCase(
                            actual
                    );
        }

        double pointsAwarded =
                correct
                        ? question.getPoints()
                        : 0.0;

        return QuestionAnswer
                .builder()
                .questionId(question.getId())
                .selectedOptionIds(
                        selectedOptionIds
                )
                .textAnswer(textAnswer)
                .correct(correct)
                .pointsAwarded(pointsAwarded)
                .answeredAt(gradedAt)
                .build();
    }

    // ============================================================
    // QUIZ ATTEMPT RESPONSE
    // ============================================================

    private QuizAttemptResponse
    toQuizAttemptResponse(
            QuizAttempt attempt,
            Quiz quiz
    ) {

        Map<String, QuizQuestion>
                questionsById =
                new LinkedHashMap<>();

        if (quiz.getQuestions() != null) {

            for (QuizQuestion question :
                    quiz.getQuestions()) {

                questionsById.put(
                        question.getId(),
                        question
                );
            }
        }

        List<QuestionAnswerResponse>
                answerResponses =
                attempt.getAnswers() == null
                        ? List.of()
                        : attempt.getAnswers()
                        .stream()
                        .map(
                                answer ->
                                        toAnswerResponseWithAnswerKey(
                                                answer,
                                                questionsById.get(
                                                        answer.getQuestionId()
                                                )
                                        )
                        )
                        .toList();

        return QuizAttemptResponse
                .builder()
                .id(attempt.getId())
                .userId(attempt.getUserId())
                .quizId(attempt.getQuizId())
                .quizTitle(attempt.getQuizTitle())
                .answers(answerResponses)
                .totalQuestions(
                        attempt.getTotalQuestions()
                )
                .correctAnswers(
                        attempt.getCorrectAnswers()
                )
                .score(attempt.getScore())
                .maxScore(attempt.getMaxScore())
                .status(attempt.getStatus())
                .startedAt(attempt.getStartedAt())
                .submittedAt(attempt.getSubmittedAt())
                .durationSeconds(
                        attempt.getDurationSeconds()
                )
                .createdAt(attempt.getCreatedAt())
                .updatedAt(attempt.getUpdatedAt())
                .build();
    }

    // ============================================================
    // ANSWER REVIEW
    // ============================================================

    private QuestionAnswerResponse
    toAnswerResponseWithAnswerKey(
            QuestionAnswer answer,
            QuizQuestion question
    ) {

        List<String> correctOptionIds =
                null;

        String correctAnswerText =
                null;

        String explanation =
                null;

        if (question != null) {

            // ----------------------------------------------------
            // Option-based question
            // ----------------------------------------------------

            if (requiresOptions(
                    question.getQuestionType()
            )) {

                if (question.getOptions() != null) {

                    correctOptionIds =
                            question.getOptions()
                                    .stream()
                                    .filter(
                                            QuizOption::isCorrect
                                    )
                                    .map(
                                            QuizOption::getId
                                    )
                                    .toList();
                }

            } else {

                // ------------------------------------------------
                // Text question
                // ------------------------------------------------

                correctAnswerText =
                        question.getCorrectAnswer();
            }

            explanation =
                    question.getExplanation();
        }

        return QuestionAnswerResponse
                .builder()
                .questionId(
                        answer.getQuestionId()
                )
                .selectedOptionIds(
                        answer.getSelectedOptionIds()
                )
                .textAnswer(
                        answer.getTextAnswer()
                )
                .correct(
                        answer.getCorrect()
                )
                .pointsAwarded(
                        answer.getPointsAwarded()
                )
                .answeredAt(
                        answer.getAnsweredAt()
                )
                .correctOptionIds(
                        correctOptionIds
                )
                .correctAnswerText(
                        correctAnswerText
                )
                .explanation(
                        explanation
                )
                .build();
    }

    // ============================================================
    // QUIZ HISTORY
    // ============================================================

    @Override
    public PageResponse getHistory(
            String requesterEmail,
            int page,
            int size
    ) {

        User requester =
                requireUser(requesterEmail);

        Pageable pageable =
                PageRequest.of(page, size);

        Page<QuizAttempt> attempts =
                quizAttemptRepository
                        .findByUserIdOrderByCreatedAtDesc(
                                requester.getId(),
                                pageable
                        );

        return PageResponse.of(
                attempts,
                this::toSummaryResponse
        );
    }

    // ============================================================
    // HISTORY SUMMARY
    // ============================================================

    private QuizAttemptSummaryResponse
    toSummaryResponse(
            QuizAttempt attempt
    ) {

        return QuizAttemptSummaryResponse
                .builder()
                .id(attempt.getId())
                .quizId(attempt.getQuizId())
                .quizTitle(attempt.getQuizTitle())
                .totalQuestions(
                        attempt.getTotalQuestions()
                )
                .correctAnswers(
                        attempt.getCorrectAnswers()
                )
                .score(attempt.getScore())
                .maxScore(
                        attempt.getMaxScore()
                )
                .status(
                        attempt.getStatus()
                )
                .startedAt(
                        attempt.getStartedAt()
                )
                .submittedAt(
                        attempt.getSubmittedAt()
                )
                .durationSeconds(
                        attempt.getDurationSeconds()
                )
                .build();
    }

    // ============================================================
    // FIND USER
    // ============================================================

    private User requireUser(
            String email
    ) {

        if (!StringUtils.hasText(email)) {

            throw new BadRequestException(
                    "Authenticated user email is required"
            );
        }

        return userRepository
                .findByEmail(email)
                .orElseThrow(
                        () ->
                                new ResourceNotFoundException(
                                        "User",
                                        "email",
                                        email
                                )
                );
    }

    // ============================================================
    // FIND QUIZ
    // ============================================================

    private Quiz requireQuiz(
            String quizId
    ) {

        if (!StringUtils.hasText(quizId)) {

            throw new BadRequestException(
                    "Quiz id is required"
            );
        }

        return quizRepository
                .findById(quizId)
                .orElseThrow(
                        () ->
                                new ResourceNotFoundException(
                                        "Quiz",
                                        "id",
                                        quizId
                                )
                );
    }
}